version: '3.1'

services:
  blog_strap_api:
    container_name: blog_strap_api
    hostname: blog_strap_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strap
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgresData/postgresonly/blog_strap_api:/var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432